version: '3'

services:
  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - postgres

  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
